### ISSUE TITLE
Gets stuck at "CREATE_IN_PROGRESS" (although most of it is installed)

### ISSUE THREAD

**Issue by rajaraodv** [aws-quickstart/saas-identity-cognito#12]
It's taken more than an hour. It is showing 34 stacks and out of which 32 are complete but two are still showing CREATE_IN_PROGRESS. Not sure how to debug. It would be great if you can help out.
Please see the picture:

<img width="1427" alt="screen shot 2018-04-01 at 10 19 01 am" src="https://user-images.githubusercontent.com/626337/38175767-926c2288-3596-11e8-928c-0845796d2e66.png">

**Comment by rajaraodv** [comment]
Never mind, it just took forever to finish. I think it about 2 hours to finish. Wondering if it's normal?

**Comment by judahb** [comment]
Please read the deployment guide. Each deployment takes about 2 hours and 15 minutes to complete. Page 12 https://s3.amazonaws.com/quickstart-reference/saas/identity/cognito/latest/doc/saas-identity-and-isolation-with-cognito-on-the-aws-cloud.pdf

**Comment by rajaraodv** [comment]
Thanks @judahb for confirming! I thought there was something wrong with the code.

**Comment by LosD** [comment]
@judahb Could a lot of the wait not be fixed by spinning up the services at the same time? AFAICT, they don't really depend on each other during spinup, so I'm not sure why each one is waiting for the other's WaitConditionXService.

Of course, once running, they very much depend on each other, but that doesn't seem like a good reason to do any waiting until the system admin creation step.
