### ISSUE TITLE
Confusing dependency relationship between user-manager service and token-manager library

### ISSUE THREAD

**Issue by aregier** [aws-quickstart/saas-identity-cognito#13]
At current, it looks like the user-manager service might have a circular dependency; Refactoring slightly here might make this micro-service architecture easier to understand and use.

At current, there is a call stack from GET /user/:id (user-manager service) -> getCredentialsForToken (token-manager) -> GET /user/pool/:id (user-manager service) -> getSystemCredentials (token-manager).

Would it potentially make sense to use dependency injection for the token-manager getCredentialsForToken function so that looking up a user pool (getUserPoolWithParams) doesn't result in another REST call when used from the user-manager service, or is this by design?

Likewise, it looks like the getSystemCredentials function in token-manager is not for widespread use and could perhaps be moved to a different shared-modules file.

**Comment by judahb** [comment]
This was by design. Ultimately, in this architecture design their is a user pool per tenant, and we need to look up what user pool configuration the tenant has to pass the appropriate params for the code. If this was a production architecture this should be implemented differently, and their may be a shared service cache with this configuration or a database lookup thats shared between these micro-services for them to look up this information in a shared table. That said, when we initially rolled this out we were trying to deliver a large number of components for describing SaaS architecture design and had time constraints, and this should be iterated and fixed. I have to prioritize internally, but I imagine this will not be changed until Q3 earliest as a result of competing priorities. I will create a new request for a feature enhancement once this gets approved, but will close for now.
