### ISSUE TITLE
CloudFormation provisioning fails for IdentityStack

### ISSUE THREAD

**Issue by hawkins6423** [aws-quickstart/saas-identity-cognito#2]
I'm getting a CREATE_FAILED during the IdentityStack provisioning. I've tried multiple regions with the recommended deployment settings. Error log:

Embedded stack arn:aws:cloudformation:us-west-2:<***>:stack/SaaS-Identity-with-Cognito-IdentityStack-1CSV9QRZNTD7R/42e6dbd0-d336-11e7-a70f-503a90a9c4d1 was not successfully created: The following resource(s) failed to create: [WaitCondition].

Any idea what this could be? The other 40 stacks were created successfully. Thanks!

**Comment by judahb** [comment]
What permissions does your IAM user have? The Quick Start expects the permissions from a System Admin role, as a result of the scope of the Quick Start.

**Comment by mictian** [comment]
Hi,
I am having exactly the same problem.

@hawkins6423  Did you solve it? How?
@judahb I am using an Administrator user, created following AWS recommendations. 

Regards,
Mictian

**Comment by judahb** [comment]
Can you confirm if each CodePipeline is completing all the required steps for each micro-service. Which region is this being run in, so i can investigate further.

**Comment by mictian** [comment]
Hi,
Thanks for your super fast replay.
1) Sorry in advance for my ignorance. But how can I check/know if the CodePipeline is completing all the required steps?
2) As recommended in the QuickStart, US West (Oregon).

**Comment by judahb** [comment]
No problem at all. Their is a service CodePipeline, which works similar to Jenkins by orchestrating a series of steps in sequence for a CI/CD Pipeline. This includes sourcing code, building docker containers, deploying these containers to EC2 Container Service, and completing a basic service availability check. There should be 8 CodePipeline configurations. 7 Micro-services, and 1 for the Web (AngularJS) application. If any one of the 7 Micro-services are not completing all steps appropriately, than the 7 expected health checks will not clear as expected, resulting in the WAIT CONDITION failing. This can happen for various reasons, however if I understand which service, and step is failing, this will allow me to resolve. Note, that we have this Quick Start running on a regular basis, and I have not seen any issues in our tool. As a result, I may need to have a quick session to identify and resolve the root cause.

**Comment by mictian** [comment]
Thank you for the explanation.

However, I still have a few questions:
1. Should I set the CF "Rollback on failure" to No?. I ask this, because I tried to deploy the quickstart again and while it was running I was able to see the different CodePiline configurations. But after it finish and automatically rollback and I couldn't see them anymore.
2. One of the services was failing due to the number of parallels builds. The fact that I have just created my AWS account can affect the number of parallel builds? (increase some limits perhaps?)
3. I couldn't find any error in the CloudWatch logs. Should it appear here?

Regards

**Comment by judahb** [comment]
1. Yes, or you can increase the wait timeout. I recommend increasing the wait timeout, as this will still rollback and remove the infrastructure reducing the cost for it to run.
2. This is possible, however by default 10 concurrent builds is the initial limit. It can't hurt to submit this request, and if this is the case I can adjust the Quick Start to resolve accordingly.
3. This depends on which step failed. If its Code Build, yes. If its Code Pipeline, not necessarily. Can you message me on Linkedin, so we can coordinate contact information. I should be able to help triage, and knock this out on a session with you sometime this week.

**Comment by hawkins6423** [comment]
Hi @judahb ,

Thanks for the reply here. Apologies it took so long for me to get back. I'm new to this as well, got a few questions:

1. Regarding the timeout, should I modify the 3600 seconds to what? 7200? Are we talking about the following WaitCondition? 
[https://github.com/aws-quickstart/saas-identity-cognito/blob/ea53e7389fa10374c472246b5b040ab983442609/templates/saas-identity-cognito.template#L447](url)

2. If the above WaitCondition timeout is a fair modification, how do I re-provision with the updated value? Clone your repo and host on my own S3 with the modified values? This is probably trivial but I just want to confirm as I've spent quite a lot of time and money trying to get this setup :)

3. Let me know if there are any logs you'd be interested in seeing. I'm available for quick call/screen share if you'd like.

**Comment by judahb** [comment]
The Root Cause has been discovered. New AWS Accounts should have a concurrent CodeBuild limit of 20 per the documentation http://docs.aws.amazon.com/codebuild/latest/userguide/limits.html , however in reality it appears as if with mictian whom i troubleshooted the issue, the service limit is 5 concurrent builds. This means, that some CodeBuilds will fail resulting in the WAIT CONDITION not succeeding within the time constraints, and providing an error. (attached) This is something that should be resolved by the CodeBuild Service Team regarding service limits, and I will submit a ticket to the Service Team to ensure that the true service limits meet the documentation service limits. As a temporary work around, please re-initiate failed builds of CodeBuild, while this has been escalated internally.

**Comment by judahb** [comment]
Internal Trouble Ticket with CodeBuild Service team has been submitted. As a temporary work-around please submit a service limit raise to 10 Concurrent Builds, or retry the failed build projects for the CodeBuild within each CodePipeline.

**Comment by hawkins6423** [comment]
@judahb ,

I didn’t see the detailed error for CodeBuild that you posted, only the error that I posted in my original post. Was this error uncovered by increasing the timeout?

Just want to make sure I’m experiencing the same issue. Based off your findings, it sounds like I am, but want to confirm.

**Comment by judahb** [comment]
@hawkins6423 Increasing the WAIT CONDITION uncovered this, however if you are within the first hour of the WAIT CONDITION after the CodePipeline stacks are created, you can still validate the same issue. View each CodeBuild project in CodePipeline, it would unveil that many of them are failing as a result of the CodeBuild Service limit. I touched base with the CodeBuild service, and they confirmed that their is a * next to the 20 concurrent build default limit, as it depends on a variety of factors such as the CodeBuild instance type, size, image, customer usage/rating, and the state of the AWS Account. New AWS Accounts appear to have an issue, when accounts that have existed for a while and in good standing have a higher rating resulting in a larger concurrent build limit. 
**To immediately fix the issue, please submit a request through the AWS Console to raise the concurrent CodeBuild Service limit to a minimum of 10 Builds.**
I will start working on a fix, which will require one CodePipeline to build at a time, which will take longer for the full stack to create, but will resolve this.

**Comment by hawkins6423** [comment]
@judahb Good info and makes sense because I created my account in November 2017 (<30 days ago). I've submitted the Service Limit request, when processed I'll retry the stack and let you know how it went. Thanks!

**Comment by mictian** [comment]
Hi,
I can confirm that after the limit raise, the deploy works like a charm :smile: 

Rergards

**Comment by hawkins6423** [comment]
I can confirm as well. 15 concurrent build service limit sufficed for me. Thanks for the help!

**Comment by judahb** [comment]
This has been resolved with this bug fix https://github.com/aws-quickstart/saas-identity-cognito/commit/5b615e6fbd65706b4436488e745fdd1d30fb0d5e
