### ISSUE TITLE
t2.micro instances instead of t2.large instances

### ISSUE THREAD

**Issue by mizalewski** [aws-quickstart/saas-identity-cognito#4]
I created QuickStart stack yesterday and surprised today that I was billed for $9. I think that many customers were surprised with this, because they can (like me) think that QuickStart uses t2.micro, which are sustainable for this. I was lucky that I saw it today, because I planned to let it running for few days and analyze working solution.

After creating stack there is 7 services with memory hard limit set to 128 MB each, which gives you just 896 MB RAM total. There is 4 t2.large instances in template, which has 8 GB RAM, 2 vCPU and cost almost 10 times more than t2.micro (can be used in this QuickStart instead).

Why just don't use t2.micro in template?

**Comment by judahb** [comment]
@mizalewski I am in progress on a fix for issue 2, and have included this in the release for that fix as well. This will provide three options for instance types t2.micro, t2.small, and t2.large. When the fix for issue 2 has been tested thoroughly, it will release with this dropdown option for these instance types.

**Comment by mizalewski** [comment]
Thanks. Great idea with dropdown!

**Comment by judahb** [comment]
This is resolved in new release. https://github.com/aws-quickstart/saas-identity-cognito/commit/5b615e6fbd65706b4436488e745fdd1d30fb0d5e
