### ISSUE TITLE
IdentityStack pre-build: compass install failed

### ISSUE THREAD

**Issue by lynatprophity** [aws-quickstart/saas-identity-cognito#48]
Hi All,

Appreciate any feedback on the following pre-build error for IdentityStack. 
This is the only step that fails in the build of either VPCStack or IdentityStack.

Here's the section where the trouble starts (bit of context before error
lines toward the bottom):

[Container] 2020/06/10 23:57:34 Running command sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass
Hit http://ppa.launchpad.net trusty InRelease
*<snip>(
Setting up ruby1.9.1 (1:1.9.3.551-556bbox1~trusty2) ...
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/gem2.2 because link group gem is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/ruby2.2 because link group ruby is broken
Setting up ruby (1:1.9.3.5bbox3~trusty1) ...  **#seems like the forced reinstalls worked?
*<snip>*
Processing triggers for libc-bin (2.19-0ubuntu6.11) ...
**ERROR:  Error installing compass:**
*<snip>*
Successfully installed rb-fsevent-0.10.4
[Container] 2020/06/10 23:58:08 Command did not exit successfully sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass exit status 1
[Container] 2020/06/10 23:58:08 Phase complete: PRE_BUILD State: FAILED
[Container] 2020/06/10 23:58:08 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass. Reason: exit status 1

The stack eventually (mostly) deletes itself after that error.
Thanks in advance for any clues.

**Comment by lynatprophity** [comment]
(That's the WebClient build.)

**Comment by jaychandran** [comment]
Hi,

I am also facing the same error. How to resolve it?

2020-06-14T10:16:43.086+05:30 | [Container] 2020/06/14 04:46:41 Command did not exit successfully sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass exit status 1
-- | --
  | 2020-06-14T10:16:43.086+05:30 | [Container] 2020/06/14 04:46:41 Phase complete: PRE_BUILD State: FAILED
  | 2020-06-14T10:16:43.086+05:30 | [Container] 2020/06/14 04:46:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass. Reason: exit status 1

@lynatprophity Lyn where you able to resolve the issue? 

Thanks!
Jay

**Comment by lynatprophity** [comment]
Hi Jay,

Unfortunately, no; haven't had time to spend since my original post. Thanks for chiming to indicate mine was not an isolated incident.

Best,
Lyn
________________________________

**Comment by jaychandran** [comment]
Hi Lyn,

There is an similar issue https://github.com/aws-quickstart/saas-identity-cognito/issues/47. I am trying to figure out how the author of that issue resolved it.

Thanks,
Jay

**Comment by pegacat** [comment]
Hi Folks,

here's an example [web-deployment-pipeline.template](https://saas-cognito.s3-ap-southeast-2.amazonaws.com/templates/web-deployment-pipeline.template) that is patched to increment the version of ruby.

I'm reluctant to post this as a formal fix, as I'm not really familiar with CloudFormation builds - the changes however are described in #47

**Comment by jaychandran** [comment]
Hi Chris,

Thank you very much for the updated template. I uploaded the Quick start to my s3 bucket along with the updated template you had provided. I have checked S3 permissions, bucket policy but the stack keep failing with below error:

```
2020-06-15 20:48:44 UTC+0530 | VPCStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
-- | -- | -- | --
```

Did you have to make any other config/roles/policy changes for the stack to be created successfully?

Thanks!
Jay

**Comment by pegacat** [comment]
Hi Jay,

sorry - I'm not an expert in AWS permissions - for the short term, maybe
make your origin bucket completely public and see if that helps?  I don't
think this is a problem with the QuickStart though; once I made the changes
to the version of ruby it ran like clockwork (fairly slow clockwork, but
still clockwork...!).

 - Chris
-----
*Dr Christopher Betts*
Melbourne, Australia
m: 61 408 533 456

**Comment by jaychandran** [comment]
Hi Chris,

I had tried with bucket being public and with full access. Will try again and see how it goes. Thanks again for your help!

Jay!

**Comment by jaychandran** [comment]
Hi Chris,

It was an issue with one of the uploaded file in S3 and after fixing that, the stack was successfully created! 

Thank you very much! 
Jay!

**Comment by pegacat** [comment]
Awesome - good work!!
-----
*Dr Christopher Betts*
Melbourne, Australia
m: 61 408 533 456

**Comment by bookables** [comment]
I still can't get the stack to create properly even with updating the template, get an error in the logs

`

Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
--
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty/main Sources
  | 2020-06-30T10:55:23.080+01:00 | Hit http://ppa.launchpad.net trusty/main amd64 Packages
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty/restricted Sources
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty/universe Sources
  | 2020-06-30T10:55:23.080+01:00 | Hit http://archive.ubuntu.com trusty/main amd64 Packages
  | 2020-06-30T10:55:25.122+01:00 | Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
  | 2020-06-30T10:55:25.122+01:00 | Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  | 2020-06-30T10:55:27.147+01:00 | Reading package lists...
  | 2020-06-30T10:55:31.172+01:00 | Reading package lists...
  | 2020-06-30T10:55:33.198+01:00 | Building dependency tree...
  | 2020-06-30T10:55:33.198+01:00 | Reading state information...
  | 2020-06-30T10:55:33.198+01:00 | The following extra packages will be installed:
  | 2020-06-30T10:55:33.198+01:00 | libgoogle-perftools-dev libgoogle-perftools4 libruby1.9.1
  | 2020-06-30T10:55:33.198+01:00 | libtcmalloc-minimal4 libunwind8 libunwind8-dev ruby1.9.1 ruby1.9.1-dev
  | 2020-06-30T10:55:33.198+01:00 | Suggested packages:
  | 2020-06-30T10:55:33.198+01:00 | ri ruby1.9.1-examples ri1.9.1 graphviz ruby-switch
  | 2020-06-30T10:55:33.198+01:00 | The following NEW packages will be installed:
  | 2020-06-30T10:55:33.198+01:00 | libgoogle-perftools-dev libgoogle-perftools4 libruby1.9.1
  | 2020-06-30T10:55:33.198+01:00 | libtcmalloc-minimal4 libunwind8 libunwind8-dev ruby ruby-dev ruby1.9.1
  | 2020-06-30T10:55:33.198+01:00 | ruby1.9.1-dev
  | 2020-06-30T10:55:35.222+01:00 | 0 upgraded, 10 newly installed, 0 to remove and 113 not upgraded.
  | 2020-06-30T10:55:35.222+01:00 | Need to get 5410 kB of archives.
  | 2020-06-30T10:55:35.222+01:00 | After this operation, 25.0 MB of additional disk space will be used.
  | 2020-06-30T10:55:35.222+01:00 | Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libunwind8 amd64 1.1-2.2ubuntu3 [48.3 kB]
  | 2020-06-30T10:55:35.222+01:00 | Get:2 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu/ trusty/main libruby1.9.1 amd64 1:1.9.3.551-556bbox1~trusty2 [2965 kB]
  | 2020-06-30T10:55:37.243+01:00 | Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libtcmalloc-minimal4 amd64 2.1-2ubuntu1.1 [103 kB]
  | 2020-06-30T10:55:37.243+01:00 | Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgoogle-perftools4 amd64 2.1-2ubuntu1.1 [184 kB]
  | 2020-06-30T10:55:37.243+01:00 | Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main libunwind8-dev amd64 1.1-2.2ubuntu3 [375 kB]
  | 2020-06-30T10:55:37.243+01:00 | Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgoogle-perftools-dev amd64 2.1-2ubuntu1.1 [407 kB]
  | 2020-06-30T10:55:37.243+01:00 | Get:7 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu/ trusty/main ruby1.9.1 amd64 1:1.9.3.551-556bbox1~trusty2 [237 kB]
  | 2020-06-30T10:55:39.269+01:00 | Get:8 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu/ trusty/main ruby all 1:1.9.3.5bbox3~trusty1 [7548 B]
  | 2020-06-30T10:55:39.269+01:00 | Get:9 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu/ trusty/main ruby1.9.1-dev amd64 1:1.9.3.551-556bbox1~trusty2 [1075 kB]
  | 2020-06-30T10:55:39.269+01:00 | Get:10 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu/ trusty/main ruby-dev all 1:1.9.3.5bbox3~trusty1 [6896 B]
  | 2020-06-30T10:55:41.291+01:00 | debconf: unable to initialize frontend: Dialog
  | 2020-06-30T10:55:41.291+01:00 | debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
  | 2020-06-30T10:55:41.291+01:00 | debconf: falling back to frontend: Readline
  | 2020-06-30T10:55:41.291+01:00 | debconf: unable to initialize frontend: Readline
  | 2020-06-30T10:55:41.291+01:00 | debconf: (This frontend requires a controlling tty.)
  | 2020-06-30T10:55:41.291+01:00 | debconf: falling back to frontend: Teletype
  | 2020-06-30T10:55:41.291+01:00 | dpkg-preconfigure: unable to re-open stdin:
  | 2020-06-30T10:55:41.291+01:00 | Fetched 5410 kB in 4s (1189 kB/s)
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libunwind8.
  | 2020-06-30T10:55:43.319+01:00 | (Reading database ... 29351 files and directories currently installed.)
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libunwind8_1.1-2.2ubuntu3_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libunwind8 (1.1-2.2ubuntu3) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libtcmalloc-minimal4.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libtcmalloc-minimal4_2.1-2ubuntu1.1_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libtcmalloc-minimal4 (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libgoogle-perftools4.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libgoogle-perftools4_2.1-2ubuntu1.1_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libgoogle-perftools4 (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libunwind8-dev.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libunwind8-dev_1.1-2.2ubuntu3_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libunwind8-dev (1.1-2.2ubuntu3) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libgoogle-perftools-dev.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libgoogle-perftools-dev_2.1-2ubuntu1.1_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libgoogle-perftools-dev (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package libruby1.9.1.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../libruby1.9.1_1%3a1.9.3.551-556bbox1~trusty2_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking libruby1.9.1 (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package ruby1.9.1.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../ruby1.9.1_1%3a1.9.3.551-556bbox1~trusty2_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking ruby1.9.1 (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package ruby.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../ruby_1%3a1.9.3.5bbox3~trusty1_all.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking ruby (1:1.9.3.5bbox3~trusty1) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package ruby1.9.1-dev.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../ruby1.9.1-dev_1%3a1.9.3.551-556bbox1~trusty2_amd64.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking ruby1.9.1-dev (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:43.319+01:00 | Selecting previously unselected package ruby-dev.
  | 2020-06-30T10:55:43.319+01:00 | Preparing to unpack .../ruby-dev_1%3a1.9.3.5bbox3~trusty1_all.deb ...
  | 2020-06-30T10:55:43.319+01:00 | Unpacking ruby-dev (1:1.9.3.5bbox3~trusty1) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libunwind8 (1.1-2.2ubuntu3) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libtcmalloc-minimal4 (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libgoogle-perftools4 (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libunwind8-dev (1.1-2.2ubuntu3) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libgoogle-perftools-dev (2.1-2ubuntu1.1) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up libruby1.9.1 (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up ruby1.9.1 (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:45.349+01:00 | update-alternatives: warning: forcing reinstallation of alternative /usr/bin/gem2.2 because link group gem is broken
  | 2020-06-30T10:55:45.349+01:00 | update-alternatives: warning: forcing reinstallation of alternative /usr/bin/ruby2.2 because link group ruby is broken
  | 2020-06-30T10:55:45.349+01:00 | Setting up ruby (1:1.9.3.5bbox3~trusty1) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up ruby1.9.1-dev (1:1.9.3.551-556bbox1~trusty2) ...
  | 2020-06-30T10:55:45.349+01:00 | Setting up ruby-dev (1:1.9.3.5bbox3~trusty1) ...
  | 2020-06-30T10:55:45.349+01:00 | Processing triggers for libc-bin (2.19-0ubuntu6.11) ...
  | 2020-06-30T10:55:47.741+01:00 | ERROR: Error installing compass:
  | 2020-06-30T10:55:47.741+01:00 | ffi requires Ruby version >= 2.3.
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed sass-3.4.25
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed multi_json-1.14.1
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed compass-core-1.0.3
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed compass-import-once-1.0.5
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed chunky_png-1.3.11
  | 2020-06-30T10:55:47.741+01:00 | Successfully installed rb-fsevent-0.10.4
  | 2020-06-30T10:55:47.741+01:00 |  
  | 2020-06-30T10:55:47.741+01:00 | [Container] 2020/06/30 09:55:45 Command did not exit successfully sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass exit status 1
  | 2020-06-30T10:55:47.741+01:00 | [Container] 2020/06/30 09:55:45 Phase complete: PRE_BUILD State: FAILED
  | 2020-06-30T10:55:47.741+01:00 | [Container] 2020/06/30 09:55:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem2.2 install compass. Reason: exit status 1

`

Has anyone else managed to get it working with replacing the template?

Thanks

**Comment by pegacat** [comment]
It looks like you're still using the old template, or at least some of it -  as described in issue #47 replace the lines in the web-deployment-pipeline.template pre_build section starting at line 145 (and remove the stuff that's there up to the crazy long 'install compass' line, because it's got a bunch of stuff baked in that I think will overwrite your ruby install even if you've correctly installed ruby 2.3 already.

 this is what I did, although I wish someone from Amazon would take the time to fix this properly:

        pre_build:
          commands:
            - cd "${SERVICE_NAME}"
            - cd src
            - sudo apt-get update
            - sudo apt-get install -y python-software-properties
            - sudo apt-add-repository ppa:brightbox/ruby-ng 
            - sudo apt-get update
            - sudo apt-get install -y ruby2.3 ruby-switch
            - sudo apt-get install -y ruby2.3-dev ruby-switch
            - sudo apt-get clean
            - sudo ruby -v
            - sudo gem install compass
            - sudo npm install && sudo npm install grunt-cli && sudo npm install bower
            - ./node_modules/bower/bin/bower install --allow-root

**Comment by brtrvn** [comment]
The Ruby version was update with commit #49
